services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DOCKER_ENV=1
      - POSTGRES_HOST=db
      - POSTGRES_DB=steamlike
      - POSTGRES_USER=steamlike
      - POSTGRES_PASSWORD=steamlike
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: steamlike
      POSTGRES_USER: steamlike
      POSTGRES_PASSWORD: steamlike
    ports:
      - "5432:5432"
